### PR TITLE
fixed german typos

### PR DESCRIPTION
**Pull request by Randomdude1001**
fixed german typos at 11 monster descriptions where "- " were falsely used

### CODE REVIEW

**Comment by CarlosFdez** [comment]
Since I can't really understand german I'll accept it as is, thank you very much!

This does remind me that I do need to set up automatic data extraction and translation extraction for monsters before Iceborne is released on PC.

**Comment by Randomdude1001** [comment]
I am willing to contribute further to the project. I guess I will join you on Discord the next day to disscus what I can possibly do and what makes sense to do.

**Comment by CarlosFdez** [comment]
@Randomdude1001 I wanted to ask. I started working on updating the automatic descriptions from the game files, and it undid your changes and readded the -'s for the german language. I set my game (on PC) to German to check and it turns out they're in the game as well:

image

Is there some german specific grammar rule I should know about regarding those hyphens? Is that how german people break up lines? Is it safe to join lines that end with - globally?

**Comment by CarlosFdez** [comment]
Figured I might as well try it out. Can you take a look at https://github.com/gatheringhallstudios/MHWorldData/pull/32 and see if it looks right? If it doesn't, can you let me know what its supposed to be and send a screenshot of the game?

**Comment by Randomdude1001** [comment]
I´m happy to help with that and going to take a look at it maybe this evening (CEST timezone).

**Pull request merged**
